### ISSUE TITLE
covertile.cycle2 depends on collective.js.cycle2 1.0a1, not b1

### ISSUE THREAD

**Issue by fredvd** [collective/covertile.cycle2#14]
In collective.js.cycle2 b1 the automated adding of the cycle2 js resources has been removed and there's an upgrade step to actively wipe the entries from portal_javasscripts. 

If you now install covertile.cycle2 b1 is pulled in and cycle2 won't start.  Should covertile.cycle2 now add the resources itself (and then hope that on upgrade we use the correct dependency in metadata.xml so c.js.cycle2 removes the entries first before covertile.cycle2 adds them again and not the other way around :-P

@djowett @hvelarde

**Comment by hvelarde** [comment]
@fredvd actually I think we must rethink the whole package; I don't remember if we ended using it or not on [www.brasil2016.gov.br](http://www.brasil2016.gov.br/), but my idea is to make the tile configurable enough to cover at least 2 or 3 templates easily just by enabling or disabling some features.

@rodfersou can you help me remembering what was done?

**Comment by djowett** [comment]
@fredvd See https://github.com/collective/collective.js.cycle2/issues/5 - where we discussed removing js resources from the registry.  The implication is that covertile.cycle2 should look after either using these resources from the static folder (as @hvelarde prefers - to keep the registry clean) or register them in the JS registry (as I prefer - to benefit from the nice caching in resource registries).  I don't think we've moved forward on that decision though.  

@hvelarde is that a fair representation?

**Comment by fredvd** [comment]
Ah I see.  I was wondering how sc.photogallery was including the resources. I must say scanning the portal_javascripts registry to see if the resource is already available there and if not including it locally on the page in the javascript_head_slot . But it's a lot of extra indirection not very transparent to figure out as a developer when which resources get added.

**Comment by rodfersou** [comment]
@hvelarde yes, we extend it to create a new tile, the first carousel (with texts in the right side as pager)

**Comment by rodfersou** [comment]
@hvelarde the carousel in the bottom is the sc.photogallery tile, not covertile.cycle2

**Comment by fredvd** [comment]
@hvelarde @djowett I was wondering why with my recent pull requests CI fails in the robot tests, but that's rather obvious if the cycle2 js resources are no longer loaded as noted in this issue. 

So.... should covertile.cycle2 itself add the resources to portal_javascripts, should we copy the ways of sc.photogallery? 

For the time being I suppose we should pin covertile.cycle2 to collective.js.cycle2 1.0a1 to get the tests running again.....

**Comment by djowett** [comment]
Hi @fredvd, sorry I've been away so not able to comment.   I see your build on that branch is still failing, I don't know if it will help, but you should note that I [switched the test buildout](https://github.com/collective/covertile.cycle2/commit/4a973f33417abcb6c564a2e08ab9a99d626c241f) to follow master branch (rather than the latest release) of collective.cover.   That is probably not necessary now 1.0a11 is out & may not be helping you here, so I have no issue with you removing that if @hvelarde agrees?

**Comment by hvelarde** [comment]
just go ahead!

**Comment by djowett** [comment]
I've been thinking about this a bit and I've come to thinking that we should register the JS we need from collective.js.cycle2 in the JS registry of this product.  If another product also registers the same JS it won't be duplicated because the id is the path to the JS file which is uniquely defined in collective.js.cycle2.
I don't think we should uninstall JS from the registry because of the effect it might have on other products also depending on those resources.

Pros of using JS registry to register Javascripts from collective.js.cycle2:
- resources are cached sensibly using resource registries, so there's no risk of stale JS resources if & when they are updated.
- less lines of code in your template (no need to reference JS resources there)

Cons:
- if you uninstall covertile.cycle2 then you would have to manually deregister any JS you didn't need, but then you shouldn't do this mindlessly anyway, as other addons may also want to use them.
- could get original & minified JS  (e.g. cycle2.min.js & cycle2.js) together in the registry, but the same issue exists for using JS through multiple page templates.

@hvelarde @fredvd @rodfersou thoughts?

**Comment by djowett** [comment]
@hvelarde you said

> actually I think we must rethink the whole package; I don't remember if we ended using it or not on www.brasil2016.gov.br, but my idea is to make the tile configurable enough to cover at least 2 or 3 templates easily just by enabling or disabling some features.
> I think actually, you can (and maybe have) used cycle2 through multiple different addons (covertile.cycle2, sc.photogallery) on the same page - which is what you wanted if I understand correctly.

It seems to me that  https://github.com/collective/collective.js.cycle2/issues/1 has given you a bad impression of what happens if we register javascript in the JS registry, but I think that issue incorrectly put  the blame on a central JS registry for cycle2 center plugin being activated, when it was a problem in the HTML template @rodfersou was using in collective.nitf.  The center plugin only fires if the following attributes are on the Cycle2 div:

```
  data-cycle-center-horz="true"
  data-cycle-center-vert="true"
```

So it was a cut & paste error - which happens, no problem, but please don't let that colour your perception of using JS registry for these situations.

:-)

**Comment by djowett** [comment]
To clarify I do think that [removing the profile from covertile.js.cycle2](https://github.com/collective/collective.js.cycle2/pull/2) was the right thing to do.

**Comment by hvelarde** [comment]
@djowett sorry for not taking care of this before: the problem, IIRC, is that you don't wanted to install all Cycle2 plugins on the first place and you told me it should be better to add a configuration option to select which plugins are going to be included on the registry, similar to what collective.js.jqueryui does in its configlet.

I don't prefer to load the resources the way we did on sc.photogallery; I just needed something functional to launch the site.

we have 2 options: include everything or work on the configlet; I vote to include everything: is about 40KB in total and I don think it worth the work on the configlet.

**Comment by djowett** [comment]
@hvelarde 
I think the problem was that covertile.cycle2 didn't work out the box 
the JQueryUI style solution was an idea - but as you say too much work.

I think there's a third option:
- [x] add JS browser resources in a canonical product (collective.js.cycle2) for ALL uses of that JS library
- [ ] each addon using the JS library adds the JS resources it requires from the canonical product to the JS registry 
  (this nicely avoids duplication in the JS registry because the id in the registry is the path to the JS browser resource under collective.js.cycle)
  - [x] covertile.cycle (done in #20)
  - [ ] sc.photogallery
  - [ ] collective.nitf
  - ...
- [ ] each addon using the JS library has to code templates defensively to not activate features in Cycle 2 they don't need (this works because [Cycle 2 is Declarative](http://jquery.malsup.com/cycle2/))
  - [x] covertile.cycle 
  - [ ] sc.photogallery (to be confirmed)
  - [ ] collective.nitf (to be confirmed)
  -  ...
- [x] The JS registry merges the JS resources from the library that are required by enabled addons & leaves the rest.
- [ ] each addon needs to document that uninstallation won't deregister javascript
  - [x] covertile.cycle (in #20)
  - [ ] sc.photogallery
  - [ ] collective.nitf
  -  ...

Here's some model uninstallation instructions inspired by [uninstall instructions of ftw.mobilenavigation](https://github.com/4teamwork/ftw.mobilenavigation#uninstall))

> #### Uninstallation
> 
> This package provides an uninstall Generic Setup profile, however, it will not deregister the Cycle2 javascripts from the JS registry dependencies as they could be used by other addons. Feel free to manually uninstall these if you are sure that you no longer use them.

This isn't to say that things will break if you do things as you are already doing them in sc.photogallery -  but if you use both that and covertile.cycle2 you would be downloading cycle2 twice, but unless I read things wrong I think that would also happen if covertile.cycle2 copied sc.photogallery's method.

**Comment by hvelarde** [comment]
sounds good to me with one addition: collective.js.cycle2 should remove all registrations when uninstalled,

**Comment by djowett** [comment]
Yes, good idea!
